[Unit]
After=sys-class-unipi_modbus-unipichannel1.device
RequiresMountsFor=/run

[Service]
ExecStartPre=-/bin/mkdir -p /run/mender
ExecStartPre=-/bin/sh -c "/usr/sbin/r2k -p 50200 -r | gunzip - | cpio -i -u -D /run/mender"
ExecStartPre=-/bin/sh -c "/bin/chmod 600 /run/mender/*"
