#@TYPE: Machine
#@NAME: Unipi Edge PLC with CM40
#@DESCRIPTION: Machine configuration for Unipi Edge in 64 bits mode

MACHINEOVERRIDES =. "raspberrypi4:"

#MACHINE_FEATURES += "pci"
MACHINE_EXTRA_RRECOMMENDS += "\
    linux-firmware-rpidistro-bcm43455 \
    bluez-firmware-rpidistro-bcm4345c0-hcd \
    linux-firmware-rpidistro-bcm43456 \
    bluez-firmware-rpidistro-bcm4345c5-hcd \
    kernel-module-unipi-id \
    kernel-module-unipi-rfkill \
    kernel-module-unipi-mfds \
    unipi-modbus-tools \
    unipi-firmware-tools \
"
MACHINE_EXTRA_RRECOMMENDS += "${@bb.utils.contains('RPI_USE_U_BOOT', '1', 'u-boot-default-script', '', d)}"

require conf/machine/include/arm/armv8a/tune-cortexa72.inc
include conf/machine/include/rpi-base.inc

RPI_KERNEL_DEVICETREE = "broadcom/bcm2711-rpi-cm4.dtb"
RPI_KERNEL_DEVICETREE_OVERLAYS = "\
    overlays/vc4-kms-v3d-pi4.dtbo \
    overlays/unipi_uboot_tpm.dtbo \
    overlays/unipi_uboot.dtbo \
    overlays/unipi_e10300.dtbo \
    overlays/ud00cb.dtbo \
    overlays/antenna2.dtbo \
"
# install dtb and dtbo into directories (broadcom, overlays)
KERNEL_DTBVENDORED = "${@bb.utils.contains('RPI_USE_U_BOOT', '1', '1', '0', d)}"

SDIMG_KERNELIMAGE ?= "kernel8.img"
SERIAL_CONSOLES = "115200;ttyAMA1"

PREFERRED_PROVIDER_u-boot-default-script ?= "unipi-u-boot-scr"
PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot"
EXTRA_IMAGEDEPENDS += "virtual/bootloader"

UBOOT_MACHINE ?= "unipi_edge_config"

VC4DTBO ?= "vc4-kms-v3d"


RPI_EXTRA_IMAGE_BOOT_FILES = " \
        ${@bb.utils.contains('RPI_USE_U_BOOT', '1', \
                'u-boot.bin', \
                '${KERNEL_IMAGETYPE};${SDIMG_KERNELIMAGE}', d)} \
        "

KERNEL_IMAGETYPE_UBOOT ?= "Image.gz"
KERNEL_IMAGETYPE_DIRECT ?= "Image.gz"

KERNEL_BOOTCMD ?= "booti"

#ARMSTUB ?= "armstub8-gic.bin"
