diff --git a/src/Makefile b/src/Makefile
index 900df6f..0654add 100644
--- a/Makefile
+++ b/Makefile
@@ -17,9 +17,6 @@
 ##############################################################################################
 # Start of default section
 #
-CC   = $(CCPREFIX)gcc
-CP   = $(CCPREFIX)objcopy
-AS   = $(CCPREFIX)gcc -x assembler-with-cpp
 INSTALL=install
 
 ifdef PROJECT_VERSION
@@ -37,24 +34,18 @@ PY_FILES = os-configurator.py
 # Define optimisation level here
 #OPT = -Ofast # Very aggressive
 #OPT = -Os # For size
-OPT = -O2 # Medium
 
 # Define debug level here
-DBG = -g0 # No debug
 #DBG = -g # Medium debug
 #DBG = -g2 # All debug symbols 
 
 INCDIRS += ../unipi-hardware-id/include
 
 INCDIR  = $(patsubst %,-I%, $(INCDIRS))
-LIBDIR  = $(patsubst %,-L%, $(LIBDIRS))
-LIB     = $(patsubst %,-l%, $(LIBS))
 
 #OBJS  = $(SRC:.c=.o)
 
-LDFLAGS = $(LIBDIR) $(LIB)
 #CPFLAGS = -g -fomit-frame-pointer -Wall -Wstrict-prototypes -fverbose-asm 
-CPFLAGS = -Wall -Wstrict-prototypes $(OPT) $(DBG)
 
 #
 # makefile rules
