#!/bin/sh

[ -z "$1" ] && exit

if [ "$1" = "upgrade_available" ]; then
   if [ "$2" = "1" ]; then
       /usr/sbin/switchboot --try
   else
       /usr/sbin/switchboot --perm
   fi
   exit $?
fi

if [ "$1" = "mender_systemd_machine_id" ]; then
    rm -f /boot/firmware/machine_id
    printf "$2" > /boot/firmware/machine_id
    exit $?
fi

if [ "$1" = "-s" ]; then
    run=$(awk '
/^upgrade_available=1/ { print "/usr/sbin/switchboot --try"; nextfile }
/^upgrade_available=0/ { print "/usr/lib/unipi/bootcount clear"; nextfile }
')
   [ -n "$run" ] && $run
fi
